dist: trusty
sudo: false

language: cpp

script:
  - sh ./build.sh
  - git checkout master
  - git add -A
  - git commit -m "deploy [ci skip]"
  - git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ${TRAVIS_BRANCH}

# TODO: add skip comment...
#deploy:
#  provider: pages
#  target-branch: master
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  on:
#    branch: master

notifications:
  email: false

env:
  global:
    - GIT_COMMITTER_NAME=srz-zumix
    - GIT_COMMITTER_EMAIL=zumix.cpp@gmail.com
    - GIT_AUTHOR_NAME=srz-zumix
    - GIT_AUTHOR_EMAIL=zumix.cpp@gmail.com
